<a href="https://colab.research.google.com/github/LeeDongGeon1996/TensorFlow/blob/master/study-note/Lab_06_1_Softmax_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

import tensorflow as tf
import numpy as np

TensorFlow 2.x selected.


In [0]:
# 8 instances, 4 features
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_features = 4
nb_classes = 3

In [0]:
tf.random.set_seed(777)
W = tf.Variable(tf.random.normal([nb_features, nb_classes], dtype = tf.float32, name="Weight"))
b = tf.Variable(tf.random.normal([nb_classes], dtype = tf.float32, name="Bias"))

print([W,b])

def softmax_classifier(features):
  return tf.nn.softmax(tf.matmul(features,W) + b)

sampled_data = np.asarray([[548,86,1,1235]], dtype = np.float32)
print(softmax_classifier(sampled_data))

def get_cost(features, labels):
  return tf.reduce_mean(-tf.reduce_sum(tf.multiply(labels, tf.math.log(softmax_classifier(features))), axis=1))

optimizer = tf.keras.optimizers.SGD(learning_rate=0.5)

def calc_grad(features, labels):
  with tf.GradientTape() as g:
    cost = get_cost(features, labels)
    grads = g.gradient(cost, [W,b])
    #print("grads : " + str(grads))
  return grads

def fit(features, labels,epochs=4000, verbose=100):
  for i in range(epochs):
    grad = calc_grad(features, labels)
    optimizer.apply_gradients(zip(grad, [W,b]))
    if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, get_cost(features, labels).numpy()))
            
fit(x_data, y_data)

[<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.7706481 ,  0.37335402, -0.05576323],
       [ 0.00358377, -0.5898363 ,  1.5702795 ],
       [ 0.2460895 , -0.09918973,  1.4418385 ],
       [ 0.3200988 ,  0.526784  , -0.7703731 ]], dtype=float32)>, <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-1.3080608 , -0.13253094,  0.5513761 ], dtype=float32)>]
tf.Tensor([[9.9999678e-01 3.1604436e-06 0.0000000e+00]], shape=(1, 3), dtype=float32)
Loss at epoch 1: 5.101215
Loss at epoch 100: 3.168825
Loss at epoch 200: 1.120199
Loss at epoch 300: 1.932226
Loss at epoch 400: 0.579747
Loss at epoch 500: 1.012704
Loss at epoch 600: 4.168036
Loss at epoch 700: 1.117758
Loss at epoch 800: 0.420168
Loss at epoch 900: 1.263011
Loss at epoch 1000: 0.762491
Loss at epoch 1100: 0.398357
Loss at epoch 1200: 0.006990
Loss at epoch 1300: 0.006817
Loss at epoch 1400: 0.006708
Loss at epoch 1500: 0.006612
Loss at epoch 1600: 0.006523
Loss at epoch 1700: 0.006438
Loss at ep

In [0]:
sample_data = [[2,1,3,2]] # answer_label [[0,0,1]]
sample_data = np.asarray(sample_data, dtype=np.float32)

a = softmax_classifier(sample_data)

print(a)
print(tf.argmax(a, 1))

tf.Tensor([[6.266717e-08 4.682882e-03 9.953171e-01]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [0]:
print(x_data)
p = softmax_classifier(x_data)
print(p)
print(tf.argmax(p, 1))
print(tf.argmax(y_data, 1)) # matches with y_data

[[1. 2. 1. 1.]
 [2. 1. 3. 2.]
 [3. 1. 3. 4.]
 [4. 1. 5. 5.]
 [1. 7. 5. 5.]
 [1. 2. 5. 6.]
 [1. 6. 6. 6.]
 [1. 7. 7. 7.]]
tf.Tensor(
[[1.2165705e-18 2.2146308e-08 1.0000000e+00]
 [6.2667169e-08 4.6828822e-03 9.9531710e-01]
 [1.8127596e-24 7.1702665e-03 9.9282974e-01]
 [7.2228170e-18 9.9289674e-01 7.1032993e-03]
 [7.5146328e-03 9.9194485e-01 5.4054451e-04]
 [3.8458416e-03 9.9615413e-01 1.6309842e-10]
 [9.9013573e-01 9.8642986e-03 4.5684935e-11]
 [9.9994612e-01 5.3892087e-05 2.5557896e-16]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


#왜 같은 값이 안나오지..

> `learning rate` 값을 적절히 조절하자. <br />
충분한 학습이 되지 않았을 수도있다.