<a href="https://colab.research.google.com/github/LeeDongGeon1996/TensorFlow/blob/master/study-note/Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab-03 Liner Regression and How to minimize cost LAB



In [1]:
%tensorflow_version 2.x

import tensorflow as tf
import numpy as np

TensorFlow 2.x selected.


In [12]:
def cost_func_ex(w,b,x,y):
  sum = 0
  for i in range(len(x)):
    x += (w*x[i] + b - y[i]) ** 2

  return sum / (2*len(x))

# random값을 생성.
# 정규분포의 중간값과 표준편차를 지정할 수있음.
for i in range(10):
  print(tf.random.normal([1], 5, 2))


# random값을 생성.
# 정규분표를 따라 생성하나 min max를 지정하여 생성가능.
print("**************************")

for i in range(10):
  print(tf.random.uniform([1], 3, 7))

tf.Tensor([7.1337605], shape=(1,), dtype=float32)
tf.Tensor([1.3917427], shape=(1,), dtype=float32)
tf.Tensor([8.397954], shape=(1,), dtype=float32)
tf.Tensor([8.22798], shape=(1,), dtype=float32)
tf.Tensor([2.6509006], shape=(1,), dtype=float32)
tf.Tensor([9.4969845], shape=(1,), dtype=float32)
tf.Tensor([3.8594117], shape=(1,), dtype=float32)
tf.Tensor([6.665659], shape=(1,), dtype=float32)
tf.Tensor([7.698511], shape=(1,), dtype=float32)
tf.Tensor([0.74439764], shape=(1,), dtype=float32)
**************************
tf.Tensor([4.2065926], shape=(1,), dtype=float32)
tf.Tensor([3.0459785], shape=(1,), dtype=float32)
tf.Tensor([6.183558], shape=(1,), dtype=float32)
tf.Tensor([5.6173], shape=(1,), dtype=float32)
tf.Tensor([4.893801], shape=(1,), dtype=float32)
tf.Tensor([4.676357], shape=(1,), dtype=float32)
tf.Tensor([4.0187635], shape=(1,), dtype=float32)
tf.Tensor([5.341142], shape=(1,), dtype=float32)
tf.Tensor([5.215643], shape=(1,), dtype=float32)
tf.Tensor([5.8761106], shape=(1,), 

In [58]:
tf.random.set_seed(0)

epoch = 500
learning_rate = 0.01
W = tf.Variable(tf.random.uniform([1], -100, 100))


x = np.array([6,7,8])
y = np.array([6,7,8])

for step in range(epoch):
  hx = W*x
  cost = tf.reduce_mean(tf.square(hx - y))
  gradient = tf.reduce_mean(tf.multiply((hx - y), x))
  W.assign(W - learning_rate * gradient)


  
  # 이 코드도 돼야하는거 아닌가...
  # W.assign_sub(learning_rate * gradient)
  
  if step % 50 == 0:
    print("{:5} | {:10.4f} | {:10.4f}".format(step, cost, W.numpy()[0]))

# Predict
print(W * [7,8,9])

    0 | 90154.1250 |   -20.4445
   50 |     0.0000 |     1.0000
  100 |     0.0000 |     1.0000
  150 |     0.0000 |     1.0000
  200 |     0.0000 |     1.0000
  250 |     0.0000 |     1.0000
  300 |     0.0000 |     1.0000
  350 |     0.0000 |     1.0000
  400 |     0.0000 |     1.0000
  450 |     0.0000 |     1.0000
tf.Tensor([7. 8. 9.], shape=(3,), dtype=float32)


### 강의에서는 H(x) = Wx로 두고 했지만,
### H(x) = Wx + b로 두고 해보자.

In [0]:
learning_rate = 0.03
epoch = 30000
W = tf.Variable(tf.random.uniform([1], -5, 10))
b = tf.Variable(tf.random.uniform([1], 2, 6))

In [79]:

x = np.array([6,7,8])
y = np.array([10,11,12])

for step in range(epoch):
  hx = W*x + b
  cost = tf.reduce_mean(tf.square(hx - y))
  # x에대한 편미분
  gradient = tf.reduce_mean(tf.multiply((hx - y), x))
  # b에대한 편미분
  gradient_b = tf.reduce_mean(tf.multiply((hx - y), 1))

  W.assign(W - learning_rate * gradient)  
  b.assign(b - learning_rate * gradient_b)
  
  if step % 500 == 0:
    print("{:5} | {:10.4f} | {:10.4f} | {:10.4f}".format(step, cost, W.numpy()[0], b.numpy()[0]))

# Predict
print(W * [7,8,9] + b)

    0 |   780.0557 |    -0.6740 |     1.2678
  500 |     0.0542 |     1.2832 |     1.9910
 1000 |     0.0365 |     1.2325 |     2.3510
 1500 |     0.0246 |     1.1908 |     2.6465
 2000 |     0.0166 |     1.1566 |     2.8890
 2500 |     0.0112 |     1.1286 |     3.0881
 3000 |     0.0075 |     1.1055 |     3.2515
 3500 |     0.0051 |     1.0866 |     3.3856
 4000 |     0.0034 |     1.0711 |     3.4957
 4500 |     0.0023 |     1.0584 |     3.5861
 5000 |     0.0016 |     1.0479 |     3.6602
 5500 |     0.0010 |     1.0393 |     3.7211
 6000 |     0.0007 |     1.0323 |     3.7711
 6500 |     0.0005 |     1.0265 |     3.8121
 7000 |     0.0003 |     1.0217 |     3.8458
 7500 |     0.0002 |     1.0178 |     3.8734
 8000 |     0.0001 |     1.0146 |     3.8961
 8500 |     0.0001 |     1.0120 |     3.9147
 9000 |     0.0001 |     1.0099 |     3.9300
 9500 |     0.0000 |     1.0081 |     3.9425
10000 |     0.0000 |     1.0066 |     3.9528
10500 |     0.0000 |     1.0055 |     3.9613
11000 |   